export enum ProductionStatus {
  DEVELOPMENT = 'DEVELOPMENT',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  PRODUCTION = 'PRODUCTION',
  POST_PRODUCTION = 'POST_PRODUCTION',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}
