export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  LOCATION_MANAGER = 'LOCATION_MANAGER',
  COSTUME_MANAGER = 'COSTUME_MANAGER',
  CAST = 'CAST',
  CREW = 'CREW',
}
